### ISSUE TITLE
Partial Results not working 

### ISSUE THREAD

**Issue by signkabob** [MicrosoftTranslator/SpeechTranslator#14] opened 2017-07-17 16:06 UTC
Thanks to the new version, media video files now work with the application. However, I found partial results function not working properly despite checking "Partial Results" option on the interface. I'm currently looking for the source of the issue.

**Comment by Fancom13** [comment] 2017-08-21 04:09
nie działa

**Comment by saikrishna-2017** [comment] 2017-12-04 06:48
@signkabob 
the issue is due to method "GetFeatures()" in MainWindow.xaml.cs which always return TimingInfo even though you select "Partial Results" on interface. 
Modify the method GetFeatures() to return string instead of enum 
private string GetFeatures()
        {
            string features = SpeechClient.Features.TimingInfo.ToString();
            string comma = ",";

            if (FeaturePartials.IsChecked.Value)
                features = features + comma + SpeechClient.Features.Partial.ToString();
            if (FeatureTTS.IsChecked.Value)
                features = features + comma + SpeechClient.Features.TextToSpeech.ToString();
            return features;
        }
 and in line 663 modify 
options.Features = GetFeatures();

I tested the above and works perfectly, hope it works same to you as well.

Sai.

**Comment by rusrc** [comment] 2018-06-06 11:21
To get partial text too just change enumeration Features as bellow:

[Flags]
public enum Features
{
TextToSpeech = 2,
Partial = 4,
TimingInfo = 8,
}

**Comment by chriswendt1** [comment] 2018-08-06 04:15
Thanks. Merged into main branch and updated binary.

**Closed by chriswendt1** 2018-08-06 04:15 UTC
